django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('feedbackapp.urls')),
    path('admin/', admin.site.urls),
]

feedbackapp/urls.py
from django.urls import path
from . import views

app_name = "feedbackapp"
urlpatterns = [
    path("", views.apply, name="apply"),
    path("login/", views.login, name="login"),
    path("home/", views.home, name="home"),
    path("logout/", views.logout, name="logout"),
    path("view/<str:id>", views.view, name="view"),
]

feedbackapp/models.py
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.db import models


def validate_mobile(value):
    if not value.startswith("6") and not value.startswith(
            "7") and not value.startswith("8") and not value.startswith("9"):
        raise ValidationError(
            _("Mobile number must start with 6,7,8 or 9"),
            params={"value": value},
        )

    if len(value) != 10:
        raise ValidationError(
            _("Mobile number must be 10 digits long"),
            params={"value": value},
        )


def validate_reg_num(value):
    if not value.startswith("VU") and not value.startswith("vu"):
        raise ValidationError(
            _("Registration number must start with VU or vu"),
            params={"value": value},
        )


class Visitor(models.Model):
    name = models.CharField(max_length=100)
    regNum = models.CharField(max_length=20)
    mobile = models.PositiveIntegerField()
    reason_for_visiting = models.TextField()
    whom_did_you_meet = models.TextField()
    description = models.TextField()
    isProblemSolved = models.BooleanField()
    rating = models.PositiveIntegerField()
    date = models.CharField(max_length=100)

    def __str__(self):
        return self.name

feedbackapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import auth
from .models import Visitor
from datetime import datetime
import pytz


def get_date_time():
    # Example date and time
    current_datetime = datetime.now(pytz.timezone("Asia/Kolkata"))

    # Format date as "DD/MM/YYYY"
    formatted_date = current_datetime.strftime("%d/%m/%Y")

    # Format time as "HH:MM AM/PM"
    formatted_time = current_datetime.strftime("%I:%M %p")

    # Combine date and time into a single string
    formatted_datetime_string = f"{formatted_date} {formatted_time}"

    return formatted_datetime_string


def apply(request):
    context = {}
    context['ids']: ['1844', '120033', '7413', '7020', '7713', '7090', '501511']
    context['names'] = [
        'Prof. Rajkumar - Associate Director (1st Year)',
        'Dr. Rajakoti - Assistant Director (1st Year)',
        'G.Srinivasa Rao - Junior Assistant',
        'B.Suresh - Junior Assistant',
        'B.Praveen Kumar - Attendant',
        'B.Appala Naidu - Attendant',
        'S.Surya Devi - Attendant',
    ]
    options = [
        "Certificate Verification", "Duplicate ID Card", "Course Registration",
        "Original TC, CC, submission (who are not submitted earlier)",
        "Admission Cancellation", "Timetables doubts", "Fee estimations",
        "Study certificates (Bank loans, Passport, Bus pass, etc…)",
        "Employee children’s bonafide certificates (Railway, Police, ARMY/NAVY, NMDC, others)",
        "Income tax exemption certificates",
        "Bus pass stamping (GITAM special & General)",
        "Bus Timings routes Information", "Moodle problems", "Coursera Issues",
        "Student portal passwords", "Email passwords", "Wifi connecting",
        "Students phone numbers changing", "Parents phone numbers changing",
        "Library Books Enquiry", "Mentors Details", "Class Teachers Details",
        "Dusters", "Markers", "Chalk piece", "NCC application stamping",
        "Sports details", "Tuition fee Issues", "Attendance Issues",
        "Marks Issues (Mid, Internals)", "RCE (Repeat Continues Evaluation)",
        "Summer Term", "Results", "Leaves enquiry",
        "Class Room for extra Class"
    ]

    context['reasons'] = options
    if request.POST:
        # print(f"\n{request.POST}\n")
        name = request.POST['name']
        regNum = request.POST['registrationnumber'].upper()
        mobile = request.POST['MobileNumber']
        reason_for_visiting = request.POST['reason_for_visiting']
        whom_did_you_meet = request.POST['whom_did_you_meet']
        description = request.POST['description']
        isProblemSolved = request.POST.get('problem_solved', False) == 'yes'
        rating = request.POST['rating']
        date = get_date_time()

        # Create a new Visitor object and save it to the database
        visitor = Visitor(
            name=name,
            regNum=regNum,
            mobile=mobile,
            reason_for_visiting=reason_for_visiting,
            whom_did_you_meet=whom_did_you_meet,
            description=description,
            isProblemSolved=isProblemSolved,
            rating=rating,
            date=date,
        )
        visitor.save()

        return render(request, 'success.html')

    return render(request, 'apply.html', context)


@login_required(login_url="feedbackapp:login")
def home(request):
    context = {}
    visitors = Visitor.objects.all()
    context['visitors'] = visitors
    return render(request, "home.html", context)


@login_required(login_url="feedbackapp:login")
def view(request, id):
    context = {}
    # visitor = Visitor.objects.get(regNum=regNum)
    visitor = get_object_or_404(Visitor, id=id)
    context['visitor'] = visitor
    return render(request, 'view.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect("feedbackapp:home")

    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect("feedbackapp:home")
        return redirect("feedbackapp:login")

    return render(request, "login.html")


@login_required(login_url="feedbackapp:login")
def logout(request):
    auth.logout(request)
    return redirect("feedbackapp:login")

templates/apply.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Feedback Form</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>
    <style>
        .gbutton {
            background-color: #9f282c;
        }

        .star-icon {
            fill: gray;
        }

        /* Define the styles for the "active" class to set the text color to yellow */
        .star-icon.active {
            fill: yellow;
        }
    </style>
</head>

<body class="h-screen">
    <nav class="bg-white border-gray-200 border-b-2 shadow-xl" style="border-color: #9f282c">
        <div class="flex items-center sm:justify-center my-2 sm:flex-grow">
            <div>
                <img src="{% static 'img/logo.png' %}" alt="" class="h-10 sm:h-16" />
            </div>
            <div class="absolute right-0 mr-3">

                {% comment %} <a href="{% url 'feedbackapp:login' %}" class="text-white text-lg px-4 py-2 rounded"
                    style="background-color: #9f282c">Login</a> {% endcomment %}
            </div>
        </div>
    </nav>
    <div class="flex flex-col">
        <div class="max-w-7xl mx-auto  px-4 sm:px-6 lg:px-8">
            <div class=" justify-center items-center">
                <h1 class="text-xl sm:text-4xl font-bold mt-5 text-center ">Please complete this form to help us improve
                    🫶</h1>
            </div>
            <form class="p-2 mt-3 sm:mt-12 space-y-4 sm:space-y-5 mr-5" method="post">
                {% csrf_token %}
                <div class="flex flex-col sm:flex-row sm:space-y-0  sm:mx-20 lg:mx-0">
                    <div class="flex flex-col space-y-1 mx-auto sm:mr-5 md:mr-10">
                        <label class="text-md font-medium" for="name">Name 👀</label>
                        <input required class="w-80 sm:w-96 px-3 py-2 border-2 border-blue-400 rounded shadow-lg"
                            type="text" placeholder="Your Name" name="name" id="name" />
                    </div>

                    <div class="flex flex-col space-y-1 sm:mr-5 mx-auto md:mr-10 mt-5 sm:mt-0">
                        <label class="text-md font-medium" for="registrationnumber">Reg No 🔟</label>
                        <input required class="w-80 sm:w-96 px-3 py-2 border-2 border-blue-400 rounded shadow-lg "
                            type="text" placeholder="Your Reg Number" name="registrationnumber"
                            id="registrationnumber" />
                    </div>
                </div>

                <div class="flex flex-col sm:flex-row  sm:space-y-0 sm:mx-20 lg:mx-0 mt-5">
                    <div class="flex flex-col space-y-1 mx-auto sm:mr-5 md:mr-10">
                        <label for="countries" class="text-md  font-medium">Mobile No 🔢</label>
                        <input required class="w-80 sm:w-96 px-3 py-2 border-2 border-blue-400 rounded shadow-lg"
                            type="number" placeholder="Mobile Number" name="MobileNumber" id="MobileNumber" />
                    </div>

                    <div class="flex flex-col space-y-1 mx-auto sm:mr-5 md:mr-10 mt-5 sm:mt-0">
                        <label for="countries" class="text-md  font-medium">Reason for Visting 🤔</label>
                        <select id="" name="reason_for_visiting" required
                            class="w-80 sm:w-96 px-3 py-2 shadow-lg border-2 border-blue-400 rounded" type="text>
              <option value=" junk">---------------</option>
                            <option value="junk">--- select ---</option>
                            {% for st in reasons %}
                            <option value="{{ st }}">{{ st }}</option>
                            {% endfor %}

                        </select>
                    </div>

                </div>
                <div class="flex flex-col sm:flex-row  sm:space-y-0 sm:mx-20 lg:mx-0 mt-5">
                    <div class="flex flex-col space-y-1 mx-auto sm:ml-0 md:ml-0">
                        <label for="whom_did_you_meet" class="text-md  font-medium">Whom did you meet 🫱‍🫲</label>

                        <select id="" name="whom_did_you_meet" required
                            class="w-80 sm:w-96 px-3 py-2 shadow-lg border-2 border-blue-400 rounded" type="text>
              <option value=" junk">---------------</option>
                            <option value="junk">--- select ---</option>
                            {% for st in names %}
                            <option value="{{ st }}">{{ st }}</option>
                            {% endfor %}

                        </select>
                    </div>
                </div>
                <div class="mt-10 flex flex-col  sm:ml-0  ">

                    <p class="text-xl my-2 text-center font-bold">Is Your Problem Solved ❓</p>
                    <div class="mx-auto">
                        <div class="flex items-center mx-auto mb-4 mx-auto">
                            <input required checked id="default-radio-1" type="radio" name="problem_solved" value="yes"
                                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500  focus:ring-2 ">
                            <label for="default-radio-1" class="ml-2 text-sm font-medium text-gray-900">Yes, My Problem
                                Solved
                            </label>
                        </div>
                        <div class="flex items-center">
                            <input required id="problem_not_solved_radio" type="radio" name="problem_solved" value="no"
                                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 focus:ring-2 ">
                            <label for="default-radio-2" class="ml-2 text-sm font-medium text-gray-900">No, My Problem
                                Not Solved</label>
                        </div>

                    </div>
                    <div class="  flex flex-col space-y-1  mx-auto ">
                        <label for="description" id="description_label" class="text-md  font-medium"> Description
                            🖊️</label>
                        <input name="description" required
                            class="w-80 sm:w-96 px-3 py-2 border-2 shadow-lg border-blue-400 rounded" type="text"
                            placeholder="Description" />
                        </select>

                    </div>
                </div>
                <div class="flex flex-col">
                    <p class="text-xl my-2 text-center font-bold">Rating</p>
                    <div class="flex items-center mx-auto space-x-1 mx-auto">
                        <svg class="w-4 h-4  star-icon" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                            fill="currentColor" viewBox="0 0 22 20">
                            <path
                                d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z" />
                        </svg>
                        <svg class="w-4 h-4  star-icon" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                            fill="currentColor" viewBox="0 0 22 20">
                            <path
                                d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z" />
                        </svg>
                        <svg class="w-4 h-4  star-icon" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                            fill="currentColor" viewBox="0 0 22 20">
                            <path
                                d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z" />
                        </svg>
                        <svg class="w-4 h-4  star-icon" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                            fill="currentColor" viewBox="0 0 22 20">
                            <path
                                d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z" />
                        </svg>
                        <svg class="w-4 h-4  star-icon" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                            fill="currentColor" viewBox="0 0 22 20">
                            <path
                                d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z" />
                        </svg>
                    </div>
                </div>

                <div class="flex w-80 sm:w-96 mx-auto py-2 mt-10">
                    <button type="submit" class="w-full text-white font-medium px-3 py-2 rounded mx-auto"
                        style="background-color: #9f282c;">Submit</button>
                </div>
                <input type="hidden" name="rating" id="rating_input" value="0">
            </form>
        </div>
    </div>
    </div>
    <script>
        const starIcons = document.querySelectorAll('.star-icon');
        const ratingInput = document.getElementById('rating_input')

        starIcons.forEach((icon, index) => {
            icon.addEventListener('click', () => {
                // Add the "active" class to the clicked icon
                icon.classList.add('active');

                // Add the "active" class to all previous icons
                for (let i = 0; i < index; i++) {
                    starIcons[i].classList.add('active');
                }

                // Remove the "active" class from all subsequent icons
                for (let i = index + 1; i < starIcons.length; i++) {
                    starIcons[i].classList.remove('active');
                }
                // Update the hidden input field value with the number of stars clicked
                ratingInput.value = index + 1;
            });
        });
    </script>

</body>

</html>

templates/form.html
<!DOCTYPE html>
<html>
<head>
    <title>Visitor Feedback Form</title>
</head>
<body>
    <h1>Visitor Feedback Form</h1>
    <form method="post">
      {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required><br>

        <label for="registration_id">Registration ID:</label>
        <input type="text" id="registration_id" name="registration_id" required><br>

        <label for="mobile_number">Mobile Number:</label>
        <input type="number" id="mobile_number" name="mobile_number" required><br>

        <label for="reason_for_visiting">Reason for Visiting:</label>
        <input type="text" id="reason_for_visiting" name="reason_for_visiting" required><br>

        <label for="whom_did_you_meet">Whom did you meet:</label>
        <input type="text" id="whom_did_you_meet" name="whom_did_you_meet" required><br>

        <label for="description">Description:</label><br>
        <textarea id="description" name="description" rows="4" cols="50" required></textarea><br>

        <label for="problem_solved">Is your problem solved?</label>
        <input type="radio" id="problem_solved_yes" name="problem_solved" value="yes" required>
        <label for="problem_solved_yes">Yes</label>
        <input type="radio" id="problem_solved_no" name="problem_solved" value="no" required>
        <label for="problem_solved_no">No</label><br>

        <label for="rating">Rating (1 to 5):</label>
        <input type="number" id="rating" name="rating" min="1" max="5" required><br>

        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home Page</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

    <style>
        .table-row-gap {
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
    <nav class="bg-white border-gray-200 border-b-2 shadow-xl" style="border-color: #9f282c">
        <div class="flex items-center sm:justify-center my-2 sm:flex-grow">
            <div>
                <img src="{% static 'img/logo.png' %}" alt="" class="ml-1 h-8 sm:h-16" />
            </div>
            <div class="absolute right-0 mr-3 ">
                <a href="{% url 'feedbackapp:home' %}"
                    class="text-black font-bold text-sm sm:text-lg pr-1 sm:px-4 py-2 rounded">Home</a>
                <a href="{% url 'feedbackapp:apply' %}"
                    class="text-black font-bold text-sm sm:text-lg pr-1 sm:px-4 py-2 rounded">Feedback Form</a>
                <a href="{% url 'feedbackapp:logout' %}" class="text-white text-lg px-2  sm:px-4 py-2 rounded"
                    style="background-color: #9f282c">Logout</a>
            </div>
        </div>
    </nav>

    <div class="container mx-auto px-4 mt-10  sm:px-6 lg:px-8">
        <div class="flex flex-col pt-30 justify-center items-center ">

            <h1 class="text-4xl font-bold mt-2  text-center " style="color: #9F282C;">Welcome to Feedback Portal</h1>
            <h1 class="text-4xl text-center font-bold mt-10">Applications</h1>

        </div>
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-4 ">
            <div class="flex flex-wrap items-center sm:justify-between justify-center">
                <div class="mt-3">

                </div>
                <div class="md:mx-0 sm:mx-auto pr-5">
                    <input type="text" id="search" onkeyup="searchTable()" placeholder="Search..."
                        class="border-2 border-gray-300 bg-white h-10 px-5 mt-3 pr-16 rounded-lg text-sm focus:outline-none ">
                </div>
            </div>
        </div>

        <div class="max-w-7xl mx-auto px-4">
            <div class="px-4 sm:px-8 py-4 overflow-x-auto">
                <div class="min-w-full overflow-auto shadow-xl">
                    <div class="space-y-4 w-full ">
                        <table id="table" class="min-w-full leading-normal border-spacing-y-4">
                            <thead>
                                <tr class="border border-black">
                                    <th
                                        class="px-5 py-5 text-left text-xs font-semibold text-black uppercase tracking-wider w-60">
                                        Name</th>
                                    <th
                                        class="px-5 py-5 text-left text-xs font-semibold text-black uppercase tracking-wider w-60">
                                        Registration Number</th>
                                    <th
                                        class="px-5 py-5 text-left text-xs font-semibold text-black uppercase tracking-wider w-60">
                                        Mobile</th>
                                    <th
                                        class="px-5 py-5 text-left text-xs font-semibold text-black uppercase tracking-wider w-60">
                                        Date</th>
                                    <th
                                        class="px-5 py-5 text-left text-xs font-semibold text-black uppercase tracking-wider w-60">
                                        Option</th>
                                </tr>
                            </thead>
                            <tbody id="tbody">

                                {% for student in visitors %}
                                <tr class="shadow-xl table-row-gap" id="tr">
                                    <td class="border-l-4 border-blue-900 px-5 py-5 text-sm w-60">{{student.name}}</td>
                                    <td class="px-5 py-5 text-sm w-60">{{student.regNum}}</td>
                                    <td class="px-5 py-5 text-sm w-60">{{ student.mobile }}</td>
                                    <td class="px-5 py-5 text-sm w-60">{{ student.date }}</td>
                                    <td class="px-5 py-5 text-sm w-60">
                                        <a href="{% url 'feedbackapp:view' student.id %}"
                                            class="bg-blue-900 text-white px-5 py-2 rounded-3xl">View</button>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
</body>
<script>


    var $rows = $(' #tbody tr');
    $('#search').keyup(function () {

        var val = '^(?=.*\\b' + $.trim($(this).val()).split(/\s+/).join('\\b)(?=.*\\b') + ').*$',
            reg = RegExp(val, 'i'),
            text;

        $rows.show().filter(function () {
            text = $(this).text().replace(/\s+/g, ' ');
            return !reg.test(text);
        }).hide();
    });

</script>

</html>

templates/navbar.html
{% load static %}

<nav class="bg-white border-gray-200 border-b-2 shadow-xl"
            style="border-color: #9F282C;">
            <div class="flex items-center justify-between mx-auto my-2">
                <div class="flex items-center justify-center sm:flex-grow">
                    <div
                        class="justify-center items-center h-10 sm:h-16 ml-2 sm:mr-0">
                        <div class="mx-auto flex justify-center">
                            <img src="{% static 'img/logo.png' %}"
                                class="sm:pl-20 h-10 sm:h-16">
                        </div>
                    </div>
                </div>
                <div class="mr-3">
                    <a href="{% url 'feedbackapp:logout' %}"
                        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 sm:py-2 px-3 sm:px-4 rounded focus:outline-none focus:shadow-outline"
                        type="submit" style="background-color: #9F282C;">
                        Log Out
                    </button>
                </div>
            </div>
        </nav>

templates/success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Successfully Registered</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link
      rel="stylesheet"
      href="https://unpkg.com/tailwindcss@2.2.7/dist/tailwind.min.css"
    />
  </head>
  <body class="bg-300">
    <div class="h-screen flex justify-center items-center">
      <div class="bg-white rounded-lg shadow-lg p-6">
        <h2 class="text-2xl font-bold mb-4">Feedback Submitted ✅</h2>
        <p class="">Feedback Submitted successfully, thank you for your time 😃</p>
      </div>
    </div>
  </body>
</html>

templates/view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>View Application</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
     <nav
      class="bg-white border-gray-200 border-b-2 shadow-xl"
      style="border-color: #9f282c"
    >
      <div class="flex items-center sm:justify-center my-2 sm:flex-grow">
        <div>
          <img src="{% static 'img/logo.png' %}" alt="" class="ml-1 h-8 sm:h-16" />
        </div>
        <div class="absolute right-0 mr-3 ">
          <a href="{% url 'feedbackapp:home' %}" class="text-black font-bold text-sm sm:text-lg pr-1 sm:px-4 py-2 rounded"
            style=>Home</a>
          <a href="{% url 'feedbackapp:apply' %}" class="text-black font-bold text-sm sm:text-lg pr-1 sm:px-4 py-2 rounded"
            style=>Feedback Form</a>
          <a
            href="{% url 'feedbackapp:logout' %}"
            class="text-white text-lg px-2  sm:px-4 py-2 rounded"
            style="background-color: #9f282c"
            >Logout</a
          >
        </div>
      </div>    
    </nav>
    
    <div class="mx-1">
      <div class="max-w-4xl mx-auto">
        <div
          class="grid grid-cols-12 grid-rows-3 gap-2 sm:gap-4 p-2 pt-1 mt-5 grid-flow-dense"
        >
          <div
            class="col-span-12 sm:col-span-8 bg-white rounded-md px-2 py-1 border border-gray-500"
          >
            <h3 class="font-semibold text-md">Name</h3>
            <p>{{visitor.name}}</p>
          </div>
          <div
            class="col-span-6 sm:col-span-4 bg-white rounded-md px-2 py-1 border border-gray-500"
          >
            <h3 class="font-semibold text-md">Registration No</h3>
            <p class>{{visitor.regNum}}</p>
          </div>
          
          <div
            class="col-span-6 sm:col-span-2 sm:col-span-2 bg-white rounded-md px-2 py-1 border border-gray-500"
          >
            <h3 class="font-semibold text-md">Mobile</h3>
            <p>{{visitor.mobile}}</p>
          </div>
          <div
            class="col-span-6 sm:col-span-4 bg-white rounded-md px-2 py-1 border border-gray-500"
          >
            <h3 class="font-semibold text-md">Reason for visiting</h3>
            <p>{{visitor.reason_for_visiting}}</p>
          </div>
         
          <div
            class="col-span-6 sm:col-span-4 sm:col-span-4 bg-white rounded-md px-2 py-1 border border-gray-500"
          >
            <h3 class="font-semibold text-md">Whom did you meet</h3>
            <p class="gap-1">{{visitor.whom_did_you_meet}}</p>
          </div>
          <div
            class="col-span-12 sm:col-span-8  bg-white rounded-md px-2 py-1 border border-gray-500"
          >
            <h3 class="font-semibold text-md">Description</h3>
            <p>{{visitor.description}}</p>
          </div>
          <div
            class="col-span-8 sm:col-span-4 bg-white rounded-md px-2 py-1 border border-gray-500"
          >
            <h3 class="font-semibold text-md">Is Problem Solved?</h3>
            {% if visitor.isProblemSolved %}
            <p>Yes, the problem is solved</p>
            {% else %}
            <p>No, the problem is not solved</p>
            {% endif %}
          </div>
          <div
            class="col-span-4 sm:col-span-2 bg-white rounded-md px-2 py-1 border border-gray-500"
          >
            <h3 class="font-semibold text-md">Rating</h3>
            <p>{{visitor.rating}}</p>
          </div>
        </div>
        
        </div>
       
         
        </div> 
        
      </div>
    
  </body>
</html>